image:
  repository: aksdemoregistry24403.azurecr.io/myapp
  tag: latest   # or use a specific Build ID from ACR
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
