image:
  repository: aksdemoregistry24403.azurecr.io/weatherappnet8
  tag: 16   # or use a specific Build ID from ACR
  pullPolicy: Always
  pullSecrets:
    - acr-auth 


service:
  type: LoadBalancer
  port: 80           # External port exposed by LoadBalancer
  targetPort: 8080   # Internal container port

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}



containerPort: 8080  # Optional custom field used in deployment.yaml