trigger:
  branches:
    include:
      - main

variables:
  - group: aks-variables

stages:
- stage: Build
  displayName: Build and Push to ACR
  jobs:
  - job: Build
    displayName: Build and Push Docker Image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

    - task: Docker@2
      displayName: Docker Build and Push to ACR
      inputs:
        containerRegistry: 'ACR-ServiceConnection'  # <-- now uses the correct Docker Registry connection
        repository: '$(acrName)/myapp'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
