trigger:
  branches:
    include:
      - main

variables:
  - group: aks-variables

stages:

- stage: Testingconnection
  displayName: Deploy to Dev using Helm
  jobs:
  - job: HelmDeploy
    displayName: Helm Deploy to Dev AKS
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          export AKS_CLUSTER_NAME="$(aksCluster)"
          export RESOURCE_GROUP="$(aksResourceGroup)"
          echo "AKS Cluster: $AKS_CLUSTER_NAME"
          echo "Resource Group: $RESOURCE_GROUP"


