trigger:
  branches:
    include:
      - main

variables:
  - group: aks-variables

stages:

- stage: Testingconnection
  displayName: Deploy to Dev using Helm
  jobs:
  - job: HelmDeploy
    displayName: Helm Deploy to Dev AKS
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "AKS Cluster: $(aksClusterName)"
          echo "Resource Group: $(resourceGroup)"
          az aks get-credentials --resource-group "$(resourceGroup)" --name "$(aksClusterName)" --overwrite-existing
          kubectl config current-context


